import * as ddl_mod from './components/ddl';
import * as ddl_mod2 from './components/ddl2';
import * as ddl_db_mod from './components/ddl_db';
import * as date_picker_mod from './components/date_picker';
import * as date_range_picker_mod from './components/date_range_picker';
import * as date_picker_style_mod from './css/date_picker_style';
import * as auto_complete_mod from './components/auto_complete';
import * as is_button_mod from './components/is_button';
import * as toggle_button_mod from './components/toggle_button';
import * as svg_path_list_mod from './components/svg_path_list';
import * as auto_complete_native_mod from './components/auto_complete_native';
import * as modal_mod from './components/modal';
import * as modal_alert_mod from './components/modal_alert';
import * as input_with_label_mod from './components/input_with_label';
import * as table_mod from './components/table/table';
import * as list_gen_mod from './components/list_gen';
import * as spinner_mod from './components/spinner';
import * as svg_mod from './components/svgs/svg';
import * as close_svg_mod from './components/svgs/close_svg';
import * as toast_mod from './components/toast';
import * as wysiwyg_mod from './components/wysiwyg';
import * as input_list_creator_mod from './components/input_list_creator';
import * as create_list_mod from './components/create_list';

import * as fb_file_uploader_mod from './components/fb_file_uploader';

// import * as layout_mod from './components/layout/layout';
import * as dom_diffing_mod from './utilities/dom_diffing';
import * as object_to_array_mod from './utilities/object_to_array';
import * as add_event_listener_mod from './utilities/add_event_listener';
import * as anonymous_user_mod from './utilities/anonymous_user';
import * as convert_style_obj_mod from './utilities/convert_style_obj';
import * as distinct_array_by_prop_mod from './utilities/distinct_array_by_prop';
import * as field_validation_mod from './utilities/field_validation';
import * as form_validation_mod from './utilities/form_validation';
import * as get_date_mod from './utilities/get_date';
import * as group_by_mod from './utilities/group_by';
import * as data_layer_mod from './utilities/data_layer';
import * as idb_keyvalue_mod from './utilities/idb_keyvalue';
import * as dom_to_json_mod from './utilities/dom_to_json';
import * as image_resize_mod from './utilities/image_resize';
import * as insert_array_mod from './utilities/insert_array';
import * as navigation_mod from './utilities/navigation';
import * as random_int_mod from './utilities/random_int';
import * as shorten_string_mod from './utilities/shorten_string';
import * as timeout_sleep_mod from './utilities/timeout_sleep';
import * as touch_mod from './utilities/touch';
import * as unique_id_mod from './utilities/unique_id';
import * as filter_between_ids_mod from './utilities/filter_between_ids';
import * as load_sw_mod from './utilities/load_sw';
import * as nn_events_mod from './utilities/nn_events';
import * as obj_to_snake_case_mod from './utilities/obj_to_snake_case';
import * as obj_to_camel_case_mod from './utilities/obj_to_camel_case';
import * as date_time_formatter_mod from './utilities/date_time_formatter';
import * as remove_class_from_all_mod from './utilities/remove_class_from_all';
import * as flex_mod from './css/flex';
import * as animations_mod from './css/animations';

export const ddl = ddl_mod.default;
export const ddl2 = ddl_mod2.default;
export const ddl_db = ddl_db_mod.default;
export const date_picker = date_picker_mod.default;
export const date_range_picker = date_range_picker_mod.default;
export const date_picker_style = date_picker_style_mod.default;
export const auto_complete = auto_complete_mod.default;
export const is_button = is_button_mod.default;
export const toggle_button = toggle_button_mod.default;
export const svg_path_list = svg_path_list_mod.default;
export const auto_complete_native = auto_complete_native_mod.default;
export const modal = modal_mod.default;
export const modal_alert = modal_alert_mod.default;
export const dom_diffing = dom_diffing_mod.default;
export const add_event_listener = add_event_listener_mod.default;
export const input_with_label = input_with_label_mod.default;
export const table = table_mod.default;
export const list_gen = list_gen_mod.default;
export const spinner = spinner_mod.default;
export const svg = svg_mod.default;
export const close_svg = close_svg_mod.default;
export const toast = toast_mod.default;
export const wysiwyg = wysiwyg_mod.default;
export const input_list_creator = input_list_creator_mod.default;
export const create_list = create_list_mod.default;

export const fb_file_uploader = fb_file_uploader_mod.default;

// export const layout = layout_mod.default;
export const anonymous_user = anonymous_user_mod.default;
export const convert_style_obj = convert_style_obj_mod.default;
export const distinct_array_by_prop = distinct_array_by_prop_mod.default;
export const field_validation = field_validation_mod.default;
export const form_validation = form_validation_mod.default;
export const get_date = get_date_mod.default;
export const group_by = group_by_mod.default;
export const data_layer = data_layer_mod.default;
export const object_to_array = object_to_array_mod.default;
export const idb_keyvalue = idb_keyvalue_mod;
export const dom_to_json = dom_to_json_mod.default;
export const image_resize = image_resize_mod.default;
export const insert_array = insert_array_mod.default;
export const navigation = navigation_mod.default;
export const random_int = random_int_mod.default;
export const shorten_string = shorten_string_mod.default;
export const timeout_sleep = timeout_sleep_mod.default;
export const touch = touch_mod.default;
export const unique_id = unique_id_mod.default;
export const filter_between_ids = filter_between_ids_mod.default;
export const load_sw = load_sw_mod.default;
export const nn_events = nn_events_mod.default;
export const obj_to_snake_case = obj_to_snake_case_mod.default;
export const obj_to_camel_case = obj_to_camel_case_mod.default;
export const date_time_formatter = date_time_formatter_mod.default;
export const remove_class_from_all = remove_class_from_all_mod.default;
export const flex = flex_mod.default;
export const animations = animations_mod.default;

// import ddl from './components/ddl';
// import modal from './components/modal';

// export  ddl

// export default { ddl, modal };
// export ddl;
// export * as ddl_mod from './components/ddl';
// export * as modal_mod from './components/modal';
// export * as input_with_label_mod from './components/input_with_label';
// export * as dom_diffing_mod from './utilities/dom_diffing';
// const dom_diffing = require('./utilities/dom_diffing');
// export default { ddl: ddl, modal: modal, dom_diffing: dom_diffing };
