import * as ddl_mod from './components/ddl';
import * as auto_complete_mod from './components/auto_complete';
import * as auto_complete_native_mod from './components/auto_complete_native';
import * as modal_mod from './components/modal';
import * as modal_alert_mod from './components/modal_alert';
import * as input_with_label_mod from './components/input_with_label';
import * as table_mod from './components/table/table';
import * as list_gen_mod from './components/list_gen';
import * as spinner_mod from './components/spinner';
import * as svg_mod from './components/svg';
import * as toast_mod from './components/toast';
import * as wysiwyg_mod from './components/wysiwyg';
import * as input_list_creator_mod from './components/input_list_creator';
import * as create_list_mod from './components/create_list';
// import * as layout_mod from './components/layout/layout';
import * as dom_diffing_mod from './utilities/dom_diffing';
import * as add_event_listener_mod from './utilities/add_event_listener';
import * as anonymous_user_mod from './utilities/anonymous_user';
import * as convert_style_obj_mod from './utilities/convert_style_obj';
import * as distinct_array_by_prop_mod from './utilities/distinct_array_by_prop';
import * as field_validation_mod from './utilities/field_validation';
import * as get_date_mod from './utilities/get_date';
import * as group_by_mod from './utilities/group_by';
import * as data_layer_mod from './utilities/data_layer';
import * as idb_keyvalue_mod from './utilities/idb_keyvalue';
import * as dom_to_json_mod from './utilities/dom_to_json';
import * as image_resize_mod from './utilities/image_resize';
import * as insert_array_mod from './utilities/insert_array';
import * as navigation_mod from './utilities/navigation';
import * as random_int_mod from './utilities/random_int';
import * as shorten_string_mod from './utilities/shorten_string';
import * as timeout_sleep_mod from './utilities/timeout_sleep';
import * as touch_mod from './utilities/touch';
import * as unique_id_mod from './utilities/unique_id';
import * as load_sw_mod from './utilities/load_sw';
import * as nn_events_mod from './utilities/nn_events';
import * as flex_mod from './css/flex';
import * as animations_mod from './css/animations';

export const ddl = ddl_mod.default;
export const auto_complete = auto_complete_mod.default;
export const auto_complete_native = auto_complete_native_mod.default;
export const modal = modal_mod.default;
export const modal_alert = modal_alert_mod.default;
export const dom_diffing = dom_diffing_mod.default;
export const add_event_listener = add_event_listener_mod.default;
export const input_with_label = input_with_label_mod.default;
export const table = table_mod.default;
export const list_gen = list_gen_mod.default;
export const spinner = spinner_mod.default;
export const svg = svg_mod.default;
export const toast = toast_mod.default;
export const wysiwyg = wysiwyg_mod.default;
export const input_list_creator = input_list_creator_mod.default;
export const create_list = create_list_mod.default;
// export const layout = layout_mod.default;
export const anonymous_user = anonymous_user_mod.default;
export const convert_style_obj = convert_style_obj_mod.default;
export const distinct_array_by_prop = distinct_array_by_prop_mod.default;
export const field_validation = field_validation_mod.default;
export const get_date = get_date_mod.default;
export const group_by = group_by_mod.default;
export const data_layer = data_layer_mod.default;
export const idb_keyvalue = idb_keyvalue_mod;
export const dom_to_json = dom_to_json_mod.default;
export const image_resize = image_resize_mod.default;
export const insert_array = insert_array_mod.default;
export const navigation = navigation_mod.default;
export const random_int = random_int_mod.default;
export const shorten_string = shorten_string_mod.default;
export const timeout_sleep = timeout_sleep_mod.default;
export const touch = touch_mod.default;
export const unique_id = unique_id_mod.default;
export const load_sw = load_sw_mod.default;
export const nn_events = nn_events_mod.default;
export const flex = flex_mod.default;
export const animations = animations_mod.default;

// import ddl from './components/ddl';
// import modal from './components/modal';

// export  ddl

// export default { ddl, modal };
// export ddl;
// export * as ddl_mod from './components/ddl';
// export * as modal_mod from './components/modal';
// export * as input_with_label_mod from './components/input_with_label';
// export * as dom_diffing_mod from './utilities/dom_diffing';
// const dom_diffing = require('./utilities/dom_diffing');
// export default { ddl: ddl, modal: modal, dom_diffing: dom_diffing };
